"""Constants for the Push Data Example integration."""

DOMAIN = "garnet_tech"

DEFAULT_SCAN_INTERVAL = 60
MIN_SCAN_INTERVAL = 10


CONF_ACCOUNT = "Client ID"
CONF_SYSTEM = "System ID"
CONF_GARNETUSER = "Garnet Control user (email)"
CONF_GARNETPASS = "Garnet Control password"


UDP_PORT = 2123
SIA_BUFFERSIZE = 1024
MESSAGESERVER_TIMEOUT = 30
GARNETAPIURL = "web.garnetcontrol.app"

PARTITION_BASE_ID = 0
ZONE_BASE_ID = 10
HOWLER_BASE_ID = 50
FIREBUTTON_BASE_ID = 51
DOCTORBUTTON_BASE_ID = 52
POLICEBUTTON_BASE_ID = 53
TIMEDPANICBUTTON_BASE_ID = 54
COMM_BASE_ID = 55